applications:

  mcp-server:
    source:
      root: "upsun-mcp"
    type: 'nodejs:22'
    hooks:
      build: |
        npm run build
    web:
      commands:
        start: node build/index.js


routes:
  "https://{default}/":
    type: upstream
    upstream: "mcp-server:http"

